version: '3.9'

services:
  # Authentication and Authorization services
  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:latest
    env_file:
      - ../../.env
    depends_on:
      - postgresql
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - default

  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:latest
    env_file:
      - ../../.env
    networks:
      - default
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'bee_db_admin']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 55432:5432
    restart: on-failure
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  kafka_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  default:
    driver: bridge
